// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _testRcppArmadillo_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _testRcppArmadillo_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _testRcppArmadillo_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _testRcppArmadillo_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}
// addVectors_inPackage
Rcpp::NumericVector addVectors_inPackage(const Rcpp::NumericVector& vec1, const Rcpp::NumericVector& vec2);
RcppExport SEXP _testRcppArmadillo_addVectors_inPackage(SEXP vec1SEXP, SEXP vec2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vec1(vec1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vec2(vec2SEXP);
    rcpp_result_gen = Rcpp::wrap(addVectors_inPackage(vec1, vec2));
    return rcpp_result_gen;
END_RCPP
}
// addMatrices_inPackage
Rcpp::NumericMatrix addMatrices_inPackage(const Rcpp::NumericMatrix& mat1, const Rcpp::NumericMatrix& mat2);
RcppExport SEXP _testRcppArmadillo_addMatrices_inPackage(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(addMatrices_inPackage(mat1, mat2));
    return rcpp_result_gen;
END_RCPP
}
// addMatricesArmadillo_inPackage
arma::mat addMatricesArmadillo_inPackage(const arma::mat& mat1, const arma::mat& mat2);
RcppExport SEXP _testRcppArmadillo_addMatricesArmadillo_inPackage(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(addMatricesArmadillo_inPackage(mat1, mat2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testRcppArmadillo_rcpparma_hello_world", (DL_FUNC) &_testRcppArmadillo_rcpparma_hello_world, 0},
    {"_testRcppArmadillo_rcpparma_outerproduct", (DL_FUNC) &_testRcppArmadillo_rcpparma_outerproduct, 1},
    {"_testRcppArmadillo_rcpparma_innerproduct", (DL_FUNC) &_testRcppArmadillo_rcpparma_innerproduct, 1},
    {"_testRcppArmadillo_rcpparma_bothproducts", (DL_FUNC) &_testRcppArmadillo_rcpparma_bothproducts, 1},
    {"_testRcppArmadillo_addVectors_inPackage", (DL_FUNC) &_testRcppArmadillo_addVectors_inPackage, 2},
    {"_testRcppArmadillo_addMatrices_inPackage", (DL_FUNC) &_testRcppArmadillo_addMatrices_inPackage, 2},
    {"_testRcppArmadillo_addMatricesArmadillo_inPackage", (DL_FUNC) &_testRcppArmadillo_addMatricesArmadillo_inPackage, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_testRcppArmadillo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
