# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_testRcppArmadillo_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_testRcppArmadillo_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_testRcppArmadillo_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_testRcppArmadillo_rcpparma_bothproducts`, x)
}

addVectors_inPackage <- function(vec1, vec2) {
    .Call(`_testRcppArmadillo_addVectors_inPackage`, vec1, vec2)
}

addMatrices_inPackage <- function(mat1, mat2) {
    .Call(`_testRcppArmadillo_addMatrices_inPackage`, mat1, mat2)
}

addMatricesArmadillo_inPackage <- function(mat1, mat2) {
    .Call(`_testRcppArmadillo_addMatricesArmadillo_inPackage`, mat1, mat2)
}

